# Example Nydus server configuration file.
# Lines starting with a hash or where a hash is
# preceeded only by whitespace are comments.
# Hashes preceeded by non-whitespace characters do not
# make the rest of the line after the hash a comment

# Blank lines or whitespace-only lines are ignored
# Configuration parameters are in camelcase (although
# this is only a convention; we could theoretically have
# them in other casings).
# A line specifies only one config parameter.
# The parameter name comes first, then an equals sign,
# then the parameter value.

# So you must first have a known parameter name,
# then an equals sign, then the rest of the line is the value
# although whitespace will be stripped off the front and back
# of the value. But whitespace can exist in the middle of the
# value (although I don't anticipate having any parameters
# where you'll have good reason to do this).
# There can be whitespace before the parameter name,
# between the name and the equals, between the equals and
# the value, and after the value. All these will be ignored.

# There is no form of line continuation. Parameter value ends
# at the end of the line.
# There is no way to quote an equals sign. But only the first
# equals sign you see on a line actually separates a parameter name from
# a parameter value, and that can only come after a valid parameter
# name. So it should be fine for an equals to appear in the parameter
# value, but again there's probably no good reason to do that.

# If a config parameter is set multiple times, the last instance wins

# Ip address at which the server will be found
ServerIpAddr = 192.168.1.1

# Port on which the server is listening
Port = 2011

# Certificate chain which signs the server's
# certificate. Needed so the client will trust the server
# certificate and encryption can be used for communication.
CaChainFile = /etc/nydus/nydus-ca.crt
