.TH "nydus-server.conf" "5" "May 2025" "Christopher Irving" ""
.SH "NAME"
.LP 
/etc/nydus/nydus\-server.conf \- Configuration file for the server of the Nydus Launcher suite.
.SH "DESCRIPTION"
.LP 
The program
.BR nydus-server (1)
gets all its configuration from the file
.IR /etc/nydus/nydus\-server.conf.

This file is made up of key/value statements, one per line.
Lines starting with '#' or containing only whitespace are ignored.
Lines specifying configuration will be of the form

.RS 4
\fBParameterName\fR=\fBValue\fR
.RE 

ParameterName must be one of the parameters listed below; an unrecognised
configuration parameter will result in an error.
Parameter names consist of alphabetic characters only.

The parameter name must be followed by an equals sign, then
the value for that parameter. The line must contain nothing other than
whitespace after the value. No configuration values should contain
whitespace either.

A configuration line without an equals sign will result in an error.

A configuration file need not include every parameter which the Nydus
program can understand; each paramter has a built in default value
which the program will use if that parameter is not present in the
configuration file. However, most of these defaults, such as IP
addresses and location of certificate files, will likely not make
sense in your situation.

The debian package for the Nydus Launcher includes sample configuration
files. The default values in these files should be the same as the default
values built into the Nydus Launcher programs.

.SH "PARAMETERS"

.SS IpAddr
.RS 2
The IP address on the local machine which
.BR nydus-server
should bind to, and which instances of
.BR nydus-client (1)
will connect to for Minecraft account allocation.
Default is 192.168.1.1.
This is likely not correct for your situation.
.RE

.SS Port
.RS 2
The port on the local machine on which
.BR nydus-server
should listen for connections from instances of
.BR nydus-client.
Default is 2011.
.RE

.SS CertFile
.RS 2
The path to a file containing, in pem format, the certificate which
.BR nydus-server
will use to establish an encrypted connection
with instances of
.BR nydus-client.
.BR nydus-client
needs to be configured to trust this certificate.
(See
.BR nydus-client.conf (5).)
The path must be absolute.
This file and the private key below will ultimately be passed to
SSLContext.load_cert_chain() from Python's ssl library.
.RE

.SS CertPrivKey
.RS 2
The path to a file containing, in pem format, the private key associated
with the certificate given for
CertFile.
The path must be absolute.
This key must be kept secret and secure; anyone who
has access to it can pretend to be a trusted
.BR nydus-server.
This key and the certificate file above will ultimately be passed to
SSLContext.load_cert_chain() from Python's ssl library.
.RE

.SS McVersion
.RS 2
The version of Minecraft which instances of
.BR nydus-client
should launch once an account has been allocated to them.
Default is 1.20.6.
Special versions like OptiFine versions may be used here, provided
the right version of OptiFine is installed on the client machine.
.RE

.SS AllocTimeout
.RS 2
After this many hours, an account allocation is considered 'expired',
and will be released during the next cleanup regardless of whether
.BR nydus-client
has requested it be released. Must be a positive integer, so the minimum
allocation timeout period is 1 hour.
.RE

.SS BrowserUid
.RS 2
In order for MSAL (Microsoft Authentication Libraries) to
authenticate Microsoft accounts interactively, a browser needs
to be opened. While the Nydus Launcher in general runs as root
because it needs access to the certificates used for encrypted
client-server communication, browsers should not and often cannot
be run as root for a variety of reasons.
Instead, the interactive part of MSAL authentication will be done
as the user corresponding to the UID given with the BrowserUid
parameter. This user should be the one who is logged in to a
graphical interface when invoking
.BR nydus-server
or
.BR nydus-cli.
.RE

.SS MSALClientId
.RS 2
The Microsoft Azure Client ID used to access MSAL 
(Microsoft Authentication Libraries) for authenticating
to Xbox, and thence authenticating Minecraft accounts.
The default is intentionally meaningless; you'll have to
create your own Azure Client, get it approved to use the Minecraft
API, and enter its Client ID here.
.RE

.SS AllocFile
.RS 2
Path to a file which will be used to store the allocation database
(access tokens and allocations for Minecraft accounts) while
.BR nydus-server
is running.

Path must be absolute.

Default is
.IR /etc/nydus/nydus-alloc.csv.
This default will probably work fine, unless you want to put the
file in a special place or employ special security precautions.
If the file doesn't exist or is empty initially,
.BR nydus-server
will simply create it and fill out the allocation database accordingly.
.RE

.SS AccountsFile
.RS 2
Path to a file containing a list of Microsoft account names which
own Minecraft. All these accounts will attempt to be authenticated
for Minecraft when
.BR nydus-server
starts, and those that are successful will form the body of accounts
available to be allocated to clients.

The file must have a list of email addresses, one per line,
with no other text on each line. Each email address should be
for one Microsoft account that is to be used for running Minecraft.

Path must be absolute.

Default is
.IR /etc/nydus/ms-usernames.txt.

You can use the default file path or make your own, but you need to
make sure it exists and contains the email addresses
for all the Microsoft accounts you want to use; if the file is empty
the Nydus Launcher will have no accounts to allocate.
.RE

.SH "SEE ALSO"
.LP
.BR nydus-server (1),
.BR nydus-cli (1)
.BR nydus-client.conf (5),
