.TH "nydus-client" "1" "May 2025" "Christopher Irving" ""
.SH "NAME"
.LP 
nydus\-client \- Client program which requests a Minecraft account from the Nydus Launcher server and launchers Minecraft with it. 
.SH "SYNTAX"
.LP 
nydus\-client
.SH "DESCRIPTION"
.LP 
When
.BR nydus-client
is invoked, it will attempt to contact a Nydus Launcher server to be allocated a Minecraft account and access token.
If successful, it will launch Minecraft using that account.
Once Minecraft is closed,
.BR nydus-client
will again attempt to contact the server to release its ownership of the Minecraft account.

.BR nydus-client
has no command line arguments. All configuration is done by settings in the configuration
file found at
.IR /etc/nydus/nydus-client.conf.

See
.BR nydus-client.conf (5)
for details on the configuration file's format.

To run a Nydus Launcher server, see
.BR nydus-server (1).

.SH "SEE ALSO"
.LP
.BR nydus-client.conf (5),
.BR nydus-server (1),
.BR nydus-cli (1)
