.TH "nydus-cli" "1" "May 2025" "Christopher Irving" ""
.SH "NAME"
.LP 
nydus\-cli \- Command line interface for Nydus Launcher allocation database
.SH "SYNTAX"
.LP 
nydus\-cli [\fBcommand\fR]
.SH "DESCRIPTION"
.LP 
As the Nydus Launcher server operates, it tracks authentication tokens related to the Minecraft accounts it manages, as well as information about
which Nydus Launcher clients have been allocated the use of which Minecraft accounts.
Collectively, this information is called the "allocation database", and
is stored in a file on the disk.

.BR nydus-cli
provides a command line interface which can manually modify the
state of the allocation database.
In general,
.BR nydus-cli
should not be needed because
.BR nydus-server (1)
should manage account allocation and release properly on its own. But
.BR nydus-cli
may be useful to view how the server is behaving or in instances of
unexpected behaviour.

.BR nydus-cli
gets the configuration it needs by reading the configuration file for
.BR nydus-server,
namely,
.IR /etc/nydus/nydus-server.conf.
See
.BR nydus-server.conf (5)
for details on the configuration file's format.
Specifically,
.BR nydus-cli
uses the parameters
.BR BrowserUid,
.BR MSALClientId,
.BR AllocFile,
and
.BR AccountsFile.
.BR nydus-cli
may not work properly if these configuration parameters
are not present in the configuration file.

.SH "COMMANDS"

.SS summary
.RS 2
View a summary of the allocation database. The summary is designed
for easy human viewing, with spacing between entries, and only
showing the allocated client IP, allocated username, allocation time,
and Microsoft and Minecraft usernames associated with each account.
Tokens and token-related timestamps are ommitted for readability.
.RE

.SS summary-uuid <uuid>
.RS 2
View a summary of the allocation database, showing only the
Minecraft account with specified uuid. (Remember the uuid itself
will not appear in the summary output).
.RE

.SS summary-ip <client-ip>
.RS 2
View a summary of the allocation database, showing only accounts
allocated to the specified client IP address.
.RE

.SS view
.RS 2
View the current contents of the entire allocation database.
.RE

.SS view-uuid <uuid>
.RS 2
View the current state of the Minecraft account with specified uuid
in the allocation database.
.RE

.SS view-ip <client-ip>
.RS 2
View the current state of all Minecraft accounts allocated to the
specified client IP address in the allocation database.
.RE

.SS alloc <client-ip> <username> <uuid>
.RS 2
Allocate the Minecraft account with the specified uuid to the
client IP address and system username given. This only modifies
the allocation database; it doesn't cause the client to automatically
launch Minecraft.
.RE

.SS release-uuid <uuid>
.RS 2
Release the Minecraft account with the specified uuid from any
allocations it may have in the allocation database.
.RE

.SS release-ip <client-ip>
.RS 2
Release all Minecraft accounts which are allocated to the specified
client IP address from their allocations.
.RE

.SS cleanup
.RS 2
Perform a routine cleanup of the allocation database, as
R nydus-server
does periodically. Check that all client IPs and system usernames
to which a Minecraft account is allocated are still active, and
renew any access tokens associated with the Minecraft accounts
that are approaching their expiry.
.RE

.SS create
.RS 2
Create a new allocation database by rereading the file of Minecraft account
names and manually authenticating them, then overwriting the existing
allocation database file, as
R nydus-server
does when it starts up for the first time.
The location of the file containing a list of Minecraft accounts is found
by reading from
.IR /etc/nydus/nydus-server.conf.
.RE

.SS help
.RS 2
View a list of all the options and available commands for
.BR nydus-cli.
.RE

.SH "SEE ALSO"
.LP
.BR nydus-server.conf (5),
.BR nydus-server (1),
.BR nydus-client (1)
