.TH "nydus-test" "1" "May 2025" "Christopher Irving" ""
.SH "NAME"
.LP 
nydus\-test \- Program which performs a variety of correctness tests on the current installation of the Nydus Launcher. 
.SH "SYNTAX"
.LP 
nydus\-test
.SH "DESCRIPTION"
.LP 
There are no command line arguments to
.IR nydus-test.
When invoked, it simply runs all the unit tests created for the Nydus Launcher.

.SH "SEE ALSO"
.LP
.BR nydus-server (1),
.BR nydus-client (1),
.BR nydus-cli (1)
